export const Data = [
    {
        id:1,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:2,
        name:'Ethereum',
        price:56198.39,
        short:'BTC'
    },
    {
        id:3,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:4,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:5,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:6,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:7,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:8,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
    {
        id:9,
        name:'Bitcoin',
        price:56198.39,
        short:'BTC'
    },
]